version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: always
    ports:
      - "8123:8123"  # HTTP API
      - "9000:9000"  # Native TCP protocol
    environment:
      - CLICKHOUSE_DB=mydb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    restart: always
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mypassword
    depends_on:
      - clickhouse

volumes:
  mongo_data:
  clickhouse_data: